FROM amd64/ubuntu

# Create directory
RUN mkdir -p /presence
WORKDIR /presence

# Install and update packages
RUN apt-get update && apt-get install -y bluez git

# Install Mosquitto and friends
RUN apt-get install -y \
  libwebsockets-dev \
  libmosquitto-dev \
  mosquitto \
  mosquitto-clients

# Change script permissions
RUN chmod +x presence.sh

CMD ["presence.sh", "-p", "/config"]
